server:
  port: 9999

spring:
  jba:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/user?useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: 1234